# Change these first
owner: Aurinko-Yoxel # Your GitHub organization or username, where this repository lives
repo: aurinko-upptime # The name of this repository

sites:
  - name: Aurinko API
    url: https://api.aurinko.io/v1/health/check
  - name: BrightSync API
    url: https://sync.aurinko.io/api/v2/ping

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /aurinko-upptime
  logoUrl: /aurinko-upptime/assets/aurinko-icon.png
  name: Aurinko Upptime
  introTitle: "**Aurinko Upptime** is the uptime monitor and status page for Aurinko and BrightSync APIs."
  introMessage: "Learn more about Aurinko and BrightSync at [www.aurinko.io](https://www.aurinko.io)"
  navbar:
    - title: Status
      href: /
    - title: Aurinko Docs
      href: https://docs.aurinko.io/
    - title: BrightSync Docs
      href: https://docs.aurinko.io/brightsync

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
